server:
  port: 9001
  servlet:
    context-path: /fa

spring:
  profiles:
    active: uat
  application:
    name: fa-management
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum: 5
      maximum-pool-size: 15
      auto-commit: true
      pool-name: HikariCP
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  cache:
    jcache:
      config: classpath:ehcache.xml


mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    cache-enable: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.john.model
  mapper-locations: classpath:mappers/*
  log:
    mapper-locations: classpath:mappers/*
    type-aliases-package: cn.john.log.model



logging:
  file:
    name: /opt/logs/fa/fa-management.log


#令牌桶限流
bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 10
              time: 1
              unit: seconds
#日志模块开关
fa:
  log:
    enable: false

